import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  glowTop: {
    position: 'absolute',
    right: -140,
    top: -160,
    width: 320,
    height: 320,
    borderRadius: 999,
    backgroundColor: 'rgba(124,116,210,0.22)',
  },
  glowLeft: {
    position: 'absolute',
    left: -160,
    top: 180,
    width: 300,
    height: 300,
    borderRadius: 999,
    backgroundColor: 'rgba(92,205,255,0.16)',
  },
  glowRight: {
    position: 'absolute',
    right: -180,
    top: 520,
    width: 320,
    height: 320,
    borderRadius: 999,
    backgroundColor: 'rgba(60,150,255,0.14)',
  },
  glowBottom: {
    position: 'absolute',
    left: -140,
    bottom: -160,
    width: 320,
    height: 320,
    borderRadius: 999,
    backgroundColor: 'rgba(0,210,255,0.14)',
  },
  header: {
    paddingTop: 10,
    paddingHorizontal: 20,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backButton: {
    width: 34,
    height: 34,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(12,16,28,0.6)',
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  headerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  content: {
    paddingTop: 6,
    paddingHorizontal: 20,
    paddingBottom: 160,
    gap: 18,
  },
  heroCard: {
    borderRadius: 26,
    padding: 20,
    backgroundColor: 'rgba(16,20,34,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(159,167,255,0.28)',
    shadowColor: '#9fa7ff',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
  },
  heroBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(159,167,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(159,167,255,0.35)',
    marginBottom: 12,
  },
  heroBadgeText: {
    color: '#B1A6FF',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
  },
  heroTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
  },
  heroTitleAccent: {
    color: '#B1A6FF',
  },
  heroButton: {
    marginTop: 16,
    alignSelf: 'flex-start',
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 999,
    backgroundColor: '#B1A6FF',
  },
  heroButtonText: {
    color: '#111425',
    fontSize: 12,
    fontWeight: '700',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  sectionMeta: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  feedCard: {
    borderRadius: 22,
    padding: 16,
    backgroundColor: 'rgba(14,18,30,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  feedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  feedTag: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
  },
  feedTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 6,
  },
  feedAccent: {
    color: '#2DE0FF',
    fontWeight: '700',
  },
  feedBody: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  feedIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: 'rgba(45,216,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  savingsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  savingsTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  savingsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 18,
    backgroundColor: 'rgba(12,16,28,0.8)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  savingsInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  savingsIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: 'rgba(159,167,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  savingsText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  savingsMeta: {
    color: colors.textSecondary,
    fontSize: 10,
    marginTop: 4,
  },
  addButton: {
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: 'rgba(159,167,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  predictionCard: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: 'rgba(12,16,28,0.85)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  predictionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
  },
  predictionAccent: {
    color: '#B1A6FF',
    fontWeight: '700',
  },
  autopilotCard: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: 'rgba(10,18,30,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(45,216,255,0.22)',
  },
  autopilotTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  autopilotBody: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 6,
  },
  autopilotLink: {
    color: '#2DE0FF',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 10,
  },
  feedSpacer: {
    gap: 12,
  },
});
