import { StyleSheet } from 'react-native';
import { colors, spacing } from '../../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  glowTop: {
    position: 'absolute',
    left: -160,
    top: -180,
    width: 320,
    height: 320,
    borderRadius: 999,
    backgroundColor: 'rgba(124,116,210,0.18)',
  },
  glowRight: {
    position: 'absolute',
    right: -200,
    top: 140,
    width: 360,
    height: 360,
    borderRadius: 999,
    backgroundColor: 'rgba(53,201,255,0.14)',
  },
  glowBottom: {
    position: 'absolute',
    left: -180,
    bottom: -200,
    width: 360,
    height: 360,
    borderRadius: 999,
    backgroundColor: 'rgba(255,158,202,0.12)',
  },
  content: {
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingBottom: 160,
    gap: 22,
  },
  brandIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: 'rgba(124,116,210,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  avatarRing: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(124,116,210,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  avatarInner: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  metricCard: {
    paddingTop: 6,
  },
  metricLabel: {
    color: 'rgba(232,234,251,0.5)',
    fontSize: 12,
    letterSpacing: 1.2,
    fontWeight: '600',
    marginBottom: 8,
  },
  metricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  metricPillRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  metricValue: {
    color: colors.textPrimary,
    fontSize: 44,
    fontWeight: '700',
    letterSpacing: -1,
  },
  metricPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 22,
    backgroundColor: 'rgba(26,30,46,0.75)',
    borderWidth: 1,
    borderColor: 'rgba(143,132,255,0.35)',
    
  },
  metricPillIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(143,132,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricPillValue: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  metricPillCaption: {
    color: 'rgba(232,234,251,0.6)',
    fontSize: 10,
    lineHeight: 12,
  },
  insightCard: {
    borderRadius: 28,
    padding: 20,
    backgroundColor: 'rgba(14,20,36,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(45,216,255,0.25)',
  },
  insightCardPressed: {
    transform: [{ scale: 0.98 }],
    borderColor: 'rgba(45,216,255,0.4)',
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  insightLabel: {
    color: '#2DE0FF',
    fontSize: 12,
    letterSpacing: 0.8,
    fontWeight: '700',
  },
  insightTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
  },
  insightAccent: {
    color: '#2DE0FF',
    fontWeight: '700',
  },
  insightAccent2: {
    color: '#ACA3FF',
    fontWeight: '700',
  },
  insightButton: {
    marginTop: 18,
    alignSelf: 'flex-start',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 22,
    backgroundColor: '#B1A6FF',
  },
  insightButtonText: {
    color: '#1A1C28',
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 0.2,
  },
  insightHint: {
    color: 'rgba(232,234,251,0.6)',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.2,
    marginTop: -8,
    marginLeft:10
  },
  splitCard: {
    borderRadius: 22,
    padding: 18,
    backgroundColor: 'rgba(12,16,28,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 14,
  },
  splitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  splitLabel: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  splitValue: {
    color: 'rgba(232,234,251,0.7)',
    fontSize: 12,
    fontWeight: '600',
  },
  splitTrack: {
    height: 6,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.06)',
    marginBottom: 12,
    overflow: 'hidden',
  },
  splitFill: {
    height: '100%',
    borderRadius: 6,
  },
  splitFillFood: {
    width: '45%',
    backgroundColor: '#2DE0FF',
  },
  splitFillShopping: {
    width: '30%',
    backgroundColor: '#B1A6FF',
  },
  splitFillBills: {
    width: '25%',
    backgroundColor: '#FF9ED5',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  sectionHeaderTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  sectionHeaderAction: {
    color: '#B1A6FF',
    fontSize: 12,
    fontWeight: '700',
  },
  txnCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
    borderRadius: 20,
    backgroundColor: 'rgba(13,17,28,0.9)',
    borderWidth: 1,
  },
  txnIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  txnBody: {
    flex: 1,
    gap: 4,
  },
  txnTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  txnSubtitle: {
    color: 'rgba(232,234,251,0.55)',
    fontSize: 11,
  },
  txnRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  txnAmount: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  txnBadge: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  tabBarWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 18,
  },
  syncButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(53,201,255,0.5)',
    backgroundColor: 'rgba(53,201,255,0.15)',
  },
  syncButtonDisabled: {
    borderColor: 'rgba(140,150,170,0.3)',
    backgroundColor: 'rgba(140,150,170,0.1)',
  },
  syncText: {
    color: colors.textPrimary,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
});
