import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  glowTop: {
    position: 'absolute',
    left: -120,
    top: -120,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: 'rgba(59,154,255,0.15)',
  },
  glowRight: {
    position: 'absolute',
    right: -140,
    top: 160,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: 'rgba(172,163,255,0.16)',
  },
  glowBottom: {
    position: 'absolute',
    left: -120,
    bottom: -120,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: 'rgba(0,210,255,0.12)',
  },
  brandIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: 'rgba(124,116,210,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  avatarRing: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(124,116,210,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  avatarInner: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  content: {
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 140,
    gap: 20,
  },
  hero: {
    gap: 8,
  },
  heroTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '700',
  },
  heroSubtitle: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  segmented: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  segmentActive: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(124,116,210,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(124,116,210,0.4)',
  },
  segmentActiveText: {
    color: colors.textPrimary,
    fontWeight: '600',
    fontSize: 14,
  },
  segmentText: {
    color: colors.textSecondary,
    fontSize: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  summaryStack: {
    gap: 12,
  },
  summaryCard: {
    borderRadius: 20,
    padding: 16,
    backgroundColor: 'rgba(18,24,38,0.9)',
    borderWidth: 1,
  },
  summaryLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
  },
  summaryValue: {
    marginTop: 8,
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: '700',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    letterSpacing: 2,
    fontWeight: '700',
  },
  sectionLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  txnCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    gap: 14,
    backgroundColor: 'rgba(16,22,36,0.9)',
    borderRadius: 18,
    borderWidth: 1,
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
  },
  iconBubble: {
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBubbleImage: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  iconImage: {
    width: 26,
    height: 26,
    resizeMode: 'contain',
  },
  gradientCircle: {
    position: 'absolute',
  },
  txnBody: {
    flex: 1,
    gap: 6,
  },
  txnTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  txnMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    alignItems: 'center',
  },
  txnMeta: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
  },
  badgeText: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  txnRight: {
    alignItems: 'flex-end',
    gap: 6,
  },
  txnAmount: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  txnAmountPositive: {
    color: colors.success,
  },
  txnTime: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  weekCard: {
    borderRadius: 22,
    padding: 16,
    backgroundColor: 'rgba(14,20,34,0.9)',
    borderWidth: 1,
    gap: 10,
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
  },
  weekTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  weekIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekGhost: {
    opacity: 0.18,
  },
  weekTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  weekSubtitle: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  weekAmount: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  emptyState: {
    padding: 24,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(12,16,28,0.7)',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  emptyTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  emptyBody: {
    color: colors.textSecondary,
    fontSize: 12,
    textAlign: 'center',
  },
});
