import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  glowLeft: {
    position: 'absolute',
    left: -140,
    top: 120,
    width: 280,
    height: 280,
    borderRadius: 999,
    backgroundColor: 'rgba(123,103,255,0.3)',
  },
  glowRight: {
    position: 'absolute',
    right: -160,
    top: 200,
    width: 320,
    height: 320,
    borderRadius: 999,
    backgroundColor: 'rgba(72,200,255,0.28)',
  },
  glowTop: {
    position: 'absolute',
    right: -120,
    top: -140,
    width: 320,
    height: 320,
    borderRadius: 999,
    backgroundColor: 'rgba(172,163,255,0.3)',
  },
  glowBottom: {
    position: 'absolute',
    left: -200,
    bottom: -100,
    width: 400,
    height: 400,
    borderRadius: 999,
    backgroundColor: 'rgba(0,210,255,0.3)',
  },
  content: {
    paddingTop: 8,
    paddingHorizontal: 24,
    paddingBottom: 160,
    gap: 48,
  },
  profileHero: {
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(68,72,85,0.2)',
    paddingBottom: 33,
  },
  avatarRing: {
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 1.5,
    borderColor: 'rgba(123,103,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  avatarInner: {
    width: 78,
    height: 78,
    borderRadius: 39,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarStatus: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#1de9b6',
    borderWidth: 2,
    borderColor: colors.background,
  },
  profileName: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  profileEmailRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  profileEmail: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  profileDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#36e5ff',
  },
  editButton: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: 'rgba(159,167,255,0.18)',
  },
  editIcon: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
  },
  editText: {
    color: '#9fa7ff',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  editForm: {
    borderRadius: 24,
    padding: 18,
    backgroundColor: 'rgba(16,20,34,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  field: {
    marginBottom: 12,
  },
  label: {
    color: colors.textSecondary,
    fontSize: 11,
    marginBottom: 6,
  },
  input: {
    height: 44,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(12,16,28,0.8)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    color: colors.textPrimary,
    fontSize: 14,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  calendarButton: {
    width: 48,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(159,167,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(159,167,255,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarText: {
    color: '#E8EAFB',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  formActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  imageActions: {
    flexDirection: 'row',
    gap: 10,
  },
  imageButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(159,167,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(159,167,255,0.35)',
  },
  imageButtonText: {
    color: '#E8EAFB',
    fontSize: 12,
    fontWeight: '700',
  },
  formButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginRight: 10,
  },
  saveButton: {
    backgroundColor: '#B1A6FF',
  },
  cancelText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  saveText: {
    color: '#0B0F1A',
    fontSize: 12,
    fontWeight: '700',
  },
  subscriptionCard: {
    borderRadius: 32,
    padding: 24,
    backgroundColor: 'rgba(20,24,38,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(159,167,255,0.2)',
    position: 'relative',
    overflow: 'hidden',
  },
  subscriptionGlow: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 999,
    right: -60,
    top: -80,
    backgroundColor: 'rgba(123,103,255,0.35)',
  },
  tierRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  tierIcon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  tierText: {
    color: '#9fa7ff',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
  },
  subscriptionHeading: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 26,
  },
  subscriptionBody: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
  },
  subscriptionFooter: {
    marginTop: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  upgradeButton: {
    width: 90,
    height: 90,
    borderRadius: 18,
    backgroundColor: 'rgba(159,167,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  upgradeText: {
    color: '#9fa7ff',
    fontSize: 10,
    textAlign: 'center',
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  pricingBlock: {
    alignItems: 'flex-end',
  },
  priceOld: {
    color: colors.textSecondary,
    fontSize: 12,
    textDecorationLine: 'line-through',
  },
  priceNew: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '700',
  },
  permissionsCard: {
    borderRadius: 24,
    padding: 20,
    backgroundColor: 'rgba(22,27,42,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  permissionsTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  permissionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  permissionRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  permissionLabel: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  permissionCaption: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 4,
  },
  toggleOn: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(53,201,255,0.35)',
    padding: 3,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  toggleOff: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.08)',
    padding: 3,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  toggleKnobRight: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#2DE0FF',
  },
  toggleKnobLeft: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#B1A6FF',
  },
  dataSourcesCard: {
    borderRadius: 24,
    padding: 20,
    backgroundColor: 'rgba(22,27,42,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  dataSourcesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  dataSourcesTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  connectButton: {
    width: 82,
    height: 82,
    borderRadius: 18,
    backgroundColor: 'rgba(159,167,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  connectIcon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  connectText: {
    color: '#9fa7ff',
    fontSize: 10,
    textAlign: 'center',
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  sourceCard: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 18,
    backgroundColor: 'rgba(12,16,28,0.7)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  sourceInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sourceIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(159,167,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sourceIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  sourceTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  sourceMeta: {
    color: colors.textSecondary,
    fontSize: 10,
    marginTop: 4,
  },
  activePill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(53,201,255,0.2)',
  },
  activeText: {
    color: '#35C9FF',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  analyzingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(177,166,255,0.2)',
  },
  analyzingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#B1A6FF',
  },
  analyzingText: {
    color: '#B1A6FF',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  syncPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(53,201,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(53,201,255,0.35)',
  },
  syncText: {
    color: '#35C9FF',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  privacyCard: {
    borderRadius: 24,
    padding: 20,
    backgroundColor: 'rgba(22,27,42,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  privacyTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  privacyBody: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
  },
  privacyActions: {
    marginTop: 16,
    gap: 10,
  },
  dangerAction: {
    alignSelf: 'flex-start',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(255,110,132,0.16)',
  },
  dangerActionText: {
    color: '#FF6E84',
    fontSize: 12,
    fontWeight: '700',
  },
  permissionsRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  permissionsInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  permissionsIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(159,167,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  permissionsIconImage: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  permissionsText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  permissionsStatus: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  connectCard: {
    borderRadius: 24,
    padding: 20,
    backgroundColor: 'rgba(22,27,42,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  connectTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  connectRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  connectInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  connectIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectIcon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  connectText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  connectStatus: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  primaryAction: {
    marginTop: 18,
    alignSelf: 'flex-start',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: 'rgba(159,167,255,0.2)',
  },
  primaryActionText: {
    color: '#9fa7ff',
    fontSize: 12,
    fontWeight: '700',
  },
  activityCard: {
    borderRadius: 24,
    padding: 20,
    backgroundColor: 'rgba(22,27,42,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  activityTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  activityRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  activityInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  activityIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(159,167,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityIcon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  activityText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  activityMeta: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  actionChipRow: {
    marginTop: 16,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  actionChip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(159,167,255,0.2)',
  },
  actionChipText: {
    color: '#9fa7ff',
    fontSize: 11,
    fontWeight: '700',
  },
  preferenceCard: {
    borderRadius: 24,
    padding: 20,
    backgroundColor: 'rgba(22,27,42,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  preferenceTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  preferenceRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  preferenceInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  preferenceIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(159,167,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  preferenceIconImage: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  preferenceText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  preferenceStatus: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  preferenceActions: {
    marginTop: 16,
    flexDirection: 'row',
    gap: 10,
  },
  preferenceButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(159,167,255,0.18)',
  },
  preferenceButtonText: {
    color: '#9fa7ff',
    fontSize: 12,
    fontWeight: '700',
  },
  resetButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  resetButtonText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
});
