import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  glowLeft: {
    position: 'absolute',
    left: -32,
    top: -120,
    width: 120,
    height: 520,
    borderRadius: 999,
    backgroundColor: 'rgba(172,163,255,0.08)',
  },
  glowRight: {
    position: 'absolute',
    right: -24,
    bottom: -40,
    width: 120,
    height: 520,
    borderRadius: 999,
    backgroundColor: 'rgba(0,210,255,0.08)',
  },
  bgCircleTopRight: {
    position: 'absolute',
    right: -120,
    top: -120,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: 'rgba(159,167,255,0.18)',
  },
  bgCircleLeft: {
    position: 'absolute',
    left: -140,
    top: 140,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: 'rgba(123,103,255,0.18)',
  },
  bgCircleMidRight: {
    position: 'absolute',
    right: -120,
    top: 380,
    width: 240,
    height: 240,
    borderRadius: 999,
    backgroundColor: 'rgba(63,224,255,0.16)',
  },
  bgCircleBottomLeft: {
    position: 'absolute',
    left: -120,
    bottom: -140,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: 'rgba(0,210,255,0.16)',
  },
  content: {
    paddingTop: 18,
    paddingHorizontal: 24,
    paddingBottom: 140,
    gap: 40,
    zIndex: 1,
  },
  hero: {
    gap: 8,
  },
  heroTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '700',
  },
  heroSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  heroCard: {
    borderRadius: 48,
    padding: 33,
    backgroundColor: 'rgba(32,37,53,0.4)',
    borderWidth: 1,
    borderColor: 'rgba(232,234,251,0.05)',
    shadowColor: '#aca3ff',
    shadowOpacity: 0.25,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 20 },
  },
  cardPressed: {
    transform: [{ scale: 0.98 }],
    borderColor: 'rgba(159,167,255,0.3)',
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(55,255,255,0.1)',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  badgeIcon: {
    width: 16,
    height: 16,
  },
  badgeText: {
    color: '#6cf5ff',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  heroTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 32,
  },
  heroHighlight: {
    color: '#9fa7ff',
  },
  heroBody: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
  },
  heroButton: {
    marginTop: 20,
    backgroundColor: '#9fa7ff',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 999,
    alignSelf: 'flex-start',
  },
  heroButtonText: {
    color: '#0b0f1a',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  cardColumn: {
    gap: 24,
  },
  cardLarge: {
    borderRadius: 32,
    padding: 24,
    backgroundColor: 'rgba(20,24,38,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(45,216,255,0.2)',
    shadowColor: '#36e5ff',
    shadowOpacity: 0.15,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardIcon: {
    width: 32,
    height: 32,
  },
  cardTag: {
    color: '#36e5ff',
    fontSize: 10,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    marginTop: 16,
  },
  cardBody: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 12,
  },
  progressRow: {
    marginTop: 16,
  },
  progressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
  },
  progressFill: {
    width: '75%',
    height: '100%',
    backgroundColor: '#36e5ff',
  },
  progressLabel: {
    marginTop: 8,
    color: colors.textSecondary,
    fontSize: 11,
  },
  cardLargeAlt: {
    borderRadius: 32,
    padding: 24,
    backgroundColor: 'rgba(25,29,46,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(159,167,255,0.2)',
    shadowColor: '#9fa7ff',
    shadowOpacity: 0.2,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
  },
  cardTitleSmall: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  subRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
  },
  subLabel: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  subValue: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  secondaryButton: {
    marginTop: 18,
    backgroundColor: 'rgba(159,167,255,0.18)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    alignSelf: 'flex-start',
  },
  secondaryButtonText: {
    color: '#9fa7ff',
    fontSize: 12,
    fontWeight: '700',
  },
  spotifyCard: {
    borderRadius: 32,
    padding: 24,
    backgroundColor: 'rgba(22,27,42,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  spotifyRow: {
    flexDirection: 'row',
    gap: 14,
  },
  spotifyCoverWrap: {
    width: 54,
    height: 54,
    borderRadius: 18,
    overflow: 'hidden',
  },
  spotifyCover: {
    width: '100%',
    height: '100%',
  },
  spotifyText: {
    flex: 1,
    gap: 6,
  },
  spotifyTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  spotifySavings: {
    color: '#5cf5d2',
    fontSize: 12,
    fontWeight: '700',
  },
  spotifyBody: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  spotifyButton: {
    marginTop: 16,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: 'rgba(159,167,255,0.2)',
    alignSelf: 'flex-start',
  },
  spotifyButtonText: {
    color: '#9fa7ff',
    fontSize: 12,
    fontWeight: '700',
  },
  savingsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  savingsTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  savingsLink: {
    color: '#9fa7ff',
    fontSize: 12,
    fontWeight: '700',
  },
  savingsList: {
    gap: 12,
  },
  savingsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(14,18,30,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  savingsInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  savingsIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(159,167,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  savingsIcon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  savingsCardTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  savingsCardMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 4,
  },
  chevron: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
  },
});
